# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:07
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=4)),
                ('amounts', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=20), blank=True, null=True, size=None)),
                ('enrolled', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(verbose_name=datetime.datetime(2015, 12, 28, 20, 7, 31, 66813, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(verbose_name=datetime.datetime(2015, 12, 28, 20, 7, 31, 67904, tzinfo=utc))),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('student_earned', models.DecimalField(decimal_places=2, max_digits=20)),
                ('school_earned', models.DecimalField(decimal_places=2, max_digits=20)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tally.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('homeroom', models.CharField(blank=True, max_length=20, null=True)),
                ('adults', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None)),
                ('enrolled', models.BooleanField(default=True)),
                ('add_date', models.DateTimeField(verbose_name=datetime.datetime(2015, 12, 28, 20, 7, 31, 51591, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tally.Student'),
        ),
    ]
