# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='add_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2015, 12, 28, 20, 8, 4, 885012, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2015, 12, 28, 20, 8, 4, 886108, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='add_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2015, 12, 28, 20, 8, 4, 869623, tzinfo=utc)),
        ),
    ]
