# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0002_auto_20151228_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='add_date',
            field=models.DateTimeField(verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(verbose_name='Date purchase'),
        ),
        migrations.AlterField(
            model_name='student',
            name='add_date',
            field=models.DateTimeField(verbose_name='Date added'),
        ),
    ]
