# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0004_auto_20151228_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
