# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0005_auto_20151228_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='school_earned',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='student_earned',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
